### ISSUE TITLE
[bug] vite HMR-ing the file which defines onSetLanguageTag triggers error

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1686] opened 2023-11-21 22:32 UTC
### Problem

i am using this as a vite plugin till the official one comes out
https://github.com/albbus-stack/kit-stack/blob/main/src/lib/paraglide-plugin.ts

HMR-ing a file which defines the onSetLanguageTag callback, (in my case +layout.svelte), causing it to be re-defined, while paraglide/runtime stays the same, triggers inlangs double-define error - instead of checking if one variable !== undefined, maybe keep a list of references to defined callbacks, and check if they actually exist before throwing.

this is most likely HMR, since full refresh of the site get's rid of this error.

### Expected behavior

HMR would work on files that define onSetLanguageTag 

### Reproduction

```ts
// +layout.svelte in a sveltekit app
import { page } from '$app/stores';
import { afterNavigate } from '$app/navigation';
import { browser } from '$app/environment';

import { languageTag as getInitialLang, onSetLanguageTag, type AvailableLanguageTag } from '$paraglide/runtime';
import { getMobileNav, navWithOrigin } from '$lib/ts/nav';

import Navbar from '$lib/Navbar.svelte';
import Footer from '$lib/Footer.svelte';

let languageTag = getInitialLang();
if (browser) onSetLanguageTag(handleLanguageChange)
console.log(languageTag)
let nav = navWithOrigin($page.url.origin, languageTag)
let mobileNav = getMobileNav(nav)

function handleLanguageChange(lang: AvailableLanguageTag) {
  languageTag = lang
  nav = navWithOrigin($page.url.origin, lang)
  mobileNav = getMobileNav(nav)
}

afterNavigate(() => {
  if (!$page.url.hash) document.getElementById('layout')?.scrollTo(0, 0);
});
```
i left the part with nav in so you can see how i'm using it, although it's probabaly not relevant
later in the code, i render a component using the `nav` and `mobileNav` variables

### Other information

Vivaldi Latest Stable
Windows 10

**Comment by samuelstroschein** [comment] 2023-11-21 23:01
You are correct. The issue is related to HMR. Conditional logic doesn't help. The solution is likely to remove the throw at the cost of minimal risk for unexpected behavior. 

Closing in favor of #1660

**Closed by samuelstroschein** 2023-11-21 23:01 UTC
Labels: type: bug, effort: medium, scope: inlang/plugins
