### ISSUE TITLE
fix blog post styling

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1496] opened 2023-10-19 13:50 UTC
## Problem

Spacing of blog post content

<img width="875" alt="Bildschirmfoto 2023-10-19 um 15 48 36" src="https://github.com/inlang/monorepo/assets/34959078/045cac64-cc09-444a-bbea-cbdb82bd52cd">

## Solution

Fix spacing.

**Comment by NilsJacobsen** [comment] 2023-10-19 13:51
@floriandwt do you know what went wrong here? Do you or should I investigate?

**Comment by floriandwt** [comment] 2023-10-19 14:18
@NilsJacobsen assign me, I think I know what the problem is

**Comment by floriandwt** [comment] 2023-10-20 09:06
Should be resolved with https://github.com/inlang/monorepo/commit/0035141d6236fd466fb86392d8bdb08cabae4921 
Feel free to re open when other styling issues appear, looking good for me now.

**Closed by floriandwt** 2023-10-20 09:06 UTC
Labels: type: bug, scope: website, priority: medium
