### ISSUE TITLE
[bug] ide extension plugin not working as supposed

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1513] opened 2023-10-24 07:12 UTC
### Problem

When I activete the ide-extension plugin and reload. I get the prompt: 
```
There is no `plugin` configuration for the inlang extension. 
One of the `modules` should expose a `plugin` which has `customApi` containing `app.inlang.ideExtension`
```

@inlang/ide-extension 

### Expected behavior

When I put it in the modules it should just work after a reload.

### Reproduction

1. Checkout dogfood-marketplace
2. Get the prompt

### Other information

Extension Version: 1.13.0

```json
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": ["en"],
	"modules": [
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-paraglide-js@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern/dist/index.js"
	],
	"plugin.inlang.messageFormat": {
		"filePath": "./inlang/source-code/website/messages.json"
	}
}
```

**Comment by felixhaeberle** [comment] 2023-10-24 09:42
@openscript can you check this and write a test for it?

**Comment by openscript** [comment] 2023-10-25 09:35
No, I didn't. I didn't know this should be prioritized.

**Comment by felixhaeberle** [comment] 2023-10-25 10:35
cc @NilsJacobsen let's dive into this together after lunch.

https://www.loom.com/share/43cc74efbdd649cf81e22240410957fb – can't reproduce it on another example.

**Comment by NilsJacobsen** [comment] 2023-10-27 07:47
Are there any updates here?:)

**Comment by felixhaeberle** [comment] 2023-10-27 08:04
monorepo is still not working. will investigate further today. other examples are working fine.

**Comment by felixhaeberle** [comment] 2023-10-27 15:27
@openscript did you have any news about this?

**Comment by openscript** [comment] 2023-10-28 02:51
I didn't figure it out yet.. it's quite strange..

**Comment by felixhaeberle** [comment] 2023-10-30 14:52
FML

<img width="857" alt="Bildschirmfoto 2023-10-30 um 15 51 39" src="https://github.com/inlang/monorepo/assets/34959078/c91fc4aa-ab14-4bba-a5be-2001c0191dbb">


just in case anybody wondered what I have been up in the last 1**dot**5 days.

**Comment by felixhaeberle** [comment] 2023-10-30 19:48
fixed with https://github.com/inlang/monorepo/pull/1536

**Closed by felixhaeberle** 2023-10-30 19:48 UTC
Labels: type: bug, scope: inlang/ide-extension
