### ISSUE TITLE
[bug] Machine Translate - Module not found

### ISSUE THREAD

**Issue by jonator** [inlang/monorepo#1606] opened 2023-11-07 15:19 UTC
### Problem

<img width="1464" alt="Screenshot 2023-11-07 at 10 18 41 AM" src="https://github.com/inlang/monorepo/assets/4606373/d52b4e8f-c488-4847-8efb-0fc18932d788">

### Reproduction

Checkout osmosis frontend repo and go to `jonator/readable-error` and, in root, run `yarn machine-translate`

### Other information

This is our inlang config

```
/**
 * See https://inlang.com
 */
export async function defineConfig(env) {
  const { default: jsonPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js"
  );

  const { default: standardLintRules } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js"
  );

  return {
    referenceLanguage: "en",
    plugins: [
      jsonPlugin({
        pathPattern: "./packages/web/localizations/{language}.json",
        variableReferencePattern: ["{", "}"],
        ignore: ["__tests__"],
      }),
      standardLintRules(),
    ],
  };
}
```

**Comment by samuelstroschein** [comment] 2023-11-07 15:32
very likely related to #1526. this bug has most likely been fixed but the versions are not bumped. 

@jonator i look into this now

**Comment by samuelstroschein** [comment] 2023-11-07 16:01
problem was caused by an outdated dependency. fixed with https://github.com/osmosis-labs/osmosis-frontend/pull/2374

**Closed by samuelstroschein** 2023-11-07 16:01 UTC
Labels: type: bug
