### ISSUE TITLE
[bug] plugin i18next ModuleSettingsAreInvalidError - The settings are invalid

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1540] opened 2023-10-30 16:34 UTC
## Problem

<img width="665" alt="Bildschirmfoto 2023-10-30 um 17 31 21" src="https://github.com/inlang/monorepo/assets/34959078/79acc210-d13e-4fb4-b8fb-65cb231582b0">

<img width="1283" alt="Bildschirmfoto 2023-10-30 um 17 31 34" src="https://github.com/inlang/monorepo/assets/34959078/6afce579-e47d-4806-90ce-515dda99c946">

## Solution

An object should be allowed.

cc @inlang/plugins

**Comment by samuelstroschein** [comment] 2023-10-30 17:10
@felixhaeberle can you handle this? @jannesblobel implemented this but it seems like he forgot to add a test case?

**Comment by samuelstroschein** [comment] 2023-10-30 18:36
@felixhaeberle things have been tested that's the thing. seems like a test case was missing

**Comment by felixhaeberle** [comment] 2023-10-31 10:58
cc @inlang/plugins 

user has this issue: https://discord.com/channels/897438559458430986/1083724234142011392/1168590521791426560

**Comment by jannesblobel** [comment] 2023-10-31 11:12
I will take a look into it and keep you posted

**Comment by NilsJacobsen** [comment] 2023-10-31 11:24
It is more about settings validation than the actual plugins in resolve modules. Let me know if you run into problems. @jannesblobel

**Comment by jannesblobel** [comment] 2023-10-31 11:29
Progress: 
We tested namespaces/nested pathPatterns, and they passed. I have added another test, which also passed.

**Comment by jannesblobel** [comment] 2023-10-31 11:51
@felixhaeberle  
Can you provide an example repo?

**Comment by jannesblobel** [comment] 2023-10-31 11:52
> cc @inlang/plugins
> 
> user has this issue: https://discord.com/channels/897438559458430986/1083724234142011392/1168590521791426560

I also looked at this as Samuel did, and I can't reproduce this error either

**Comment by felixhaeberle** [comment] 2023-10-31 13:48
Reproduction: https://www.loom.com/share/b3f7536ec52544e38a5a3c97b3fa386a

**Comment by jannesblobel** [comment] 2023-10-31 13:49
Hm...  I know that the plugins worked when I merged it  
![CleanShot 2023-10-31 at 14 47 25@2x](https://github.com/inlang/monorepo/assets/72493222/53b13ffa-a1ce-4b2b-b762-5b65796e53e9)

**Comment by jannesblobel** [comment] 2023-10-31 13:59
If I am using a Js deliver link, it works fine for both plugins 
![CleanShot 2023-10-31 at 14 58 37@2x](https://github.com/inlang/monorepo/assets/72493222/1618777c-c60d-4c4f-8996-39059b48bbb5)
![CleanShot 2023-10-31 at 14 59 23@2x](https://github.com/inlang/monorepo/assets/72493222/ce77192e-76ae-495a-839b-8b8f502d048d)

**Comment by jannesblobel** [comment] 2023-10-31 14:08
hm.. it also works when I use a local plugin in our monorepo config. 
```
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": ["en", "de", "zh", "sk", "pt-BR"],
	"modules": [
		"./inlang/source-code/plugins/i18next/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern/dist/index.js"
	],
	"plugin.inlang.i18next": {
		"pathPattern": {
			"client-page": "./inlang/source-code/end-to-end-tests/inlang-nextjs/app/i18n/locales/{languageTag}/client-page.json",
			"footer": "./inlang/source-code/end-to-end-tests/inlang-nextjs/app/i18n/locales/{languageTag}/footer.json",
			"second-page": "./inlang/source-code/end-to-end-tests/inlang-nextjs/app/i18n/locales/{languageTag}/second-page.json",
			"translation": "./inlang/source-code/end-to-end-tests/inlang-nextjs/app/i18n/locales/{languageTag}/translation.json"
		}
	}
}

```

**Comment by jannesblobel** [comment] 2023-10-31 16:45
@felixhaeberle, your config is wrong. BU the error message also.

All paths have to start with a `/`,`./`or`../`
You are using `app/i18n` instead of `./app/i18n` 
This config should work 
```
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": ["en", "de"],
	"modules": [
		"./../../plugins/i18next/dist/index.js",
		"./../../message-lint-rules/emptyPattern/dist/index.js",
		"./../../message-lint-rules/identicalPattern/dist/index.js",
		"./../../message-lint-rules/missingTranslation/dist/index.js",
		"./../../message-lint-rules/messageWithoutSource/dist/index.js"
	],
	"plugin.inlang.i18next": {
		"pathPattern": {
			"client-page": "./app/i18n/locales/{languageTag}/client-page.json",
			"footer": "./app/i18n/locales/{languageTag}/footer.json",
			"second-page": "./app/i18n/locales/{languageTag}/second-page.json",
			"translation": "./app/i18n/locales/{languageTag}/translation.json"
		}
	}
}
```

I will update the error message and will close this issue as not planned

**Comment by jannesblobel** [comment] 2023-11-01 14:04
This bug should be fixed with https://github.com/inlang/monorepo/pull/1562. 

Also, the error message "expect union value" seems wrong. The regex did not match the path pattern, which should be in the error message instead of "Expect union value." Typebox generates this message, and we cannot easily change it.

**Closed by jannesblobel** 2023-11-01 14:04 UTC
Labels: type: bug, scope: inlang/plugins

**Comment by jannesblobel** [comment] 2023-11-01 14:06
@felixhaeberle 
I didn't change the settings to avoid merge conflicts. Please add the correct settings to the project.
