### ISSUE TITLE
[bug] Creating a project through the CLI fails

### ISSUE THREAD

**Issue by WarningImHack3r** [inlang/monorepo#1448] opened 2023-10-12 21:06 UTC
### Problem

A lot has changed since our last discussions and the sad event that hit us a few weeks ago.  
`sdk-js` is deprecated, the docs have changed, and the `armageddon` seems to have been merged.

I'm trying to upgrade my project to the newest Inlang, so I started by running `pnpx @inlang/cli@latest project init`. Sadly, it did not work, throwing the following error:
```
ℹ Could not auto generate project settings. Go to https://inlang.com/new to create a project.
```

I dug into the source code to figure out a possible cause, but all I could understand was what seemed to be a lot of abstractions over the creation of the `project.inlang.json` file.  
So I switched to the manual creation following the docs, which led me from this:
```javascript
/**
 * @type {import("@inlang/core/config").DefineConfig}
 */
export async function defineConfig(env) {
	const { default: pluginJson } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js"
	);

	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.11.8/dist/index.js"
	);

	const { default: standardLintRules } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js"
	);

	return {
		referenceLanguage: "en",
		plugins: [
			pluginJson({
				pathPattern: "./src/locales/{language}/*.json",
				variableReferencePattern: ["{", "}"]
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
			standardLintRules()
		]
	};
}
```
to that:
```json
{
	"$schema": "https://inlang.com/project-config-schema",
	"sourceLanguageTag": "en",
	"languageTags": ["en", "fr"],
	"modules": ["https://cdn.jsdelivr.net/npm/@inlang/plugin-json@4/dist/index.js"],
	"settings": {
		"plugin.inlang.json": {
			"pathPattern": "./src/locales/{languageTag}/*.json"
		}
	}
}
```

As far as I could tell, the `sdk-js` replacement is coming soon as `paraglide-js`, so I guess I cannot fully migrate for now.  
As for the `standardLintRules`, I couldn't find anything in the marketplace.

A second issue, introduced with this new config, is the fact that **the schema link is a 404** page, so it's not really helpful unfortunately :/

Lastly, it would be great to have a dedicated `Migration` page in the docs, in order to explain in a few lines what's changed from the pre-armageddon Inlang (about `sdk-js` deprecation - which you could link in the npmjs.org deprecation message, the new config, what's gone, what's new, how is it better, etc)

Good luck with the rest - Paraglide!

### Expected behavior

- The CLI's `project init` command to work
	- Or at least the error to be more meaningful instead of redirecting to a [inlang.com/new](https://inlang.com/new) that does not exist, maybe suggesting to manually create that config file?
- The docs to explain what this `project init` command is supposed to do (more than creating the config file?)
- The JSON schema link to be valid
- The `sdk-js` not to be deprecated if `paraglide-js` is not ready yet? Can I use Inlang without paraglide?
- The docs to potentially include a `Migration` page
- And what do I do for `standardLintRules`?

### Reproduction

Follow the [docs](https://inlang.com/documentation/manually-create-project)

### Other information

macOS 14.0, Node.js 20.8.0, [project link](https://github.com/EmeraldHQ/Website)

**Comment by felixhaeberle** [comment] 2023-10-13 08:01
@WarningImHack3r Thank you for this helpful feedback! 🔥

> The CLI's project init command to work
Or at least the error to be more meaningful instead of redirecting to a [inlang.com/new](https://inlang.com/new) that does not exist, maybe suggesting to manually create that config file?

We are currently in the process of rebuilding our website and will soon offer an `inlang.com/new` where we guide you through the process of creating your inlang project. Sorry if that's not helpful for you atm, but we will have something ready in a matter of a few (2-3) weeks.

> The docs to explain what this project init command is supposed to do (more than creating the config file?)

It does generate a `project.inlang.json` file for you but only if the process succeeds & the file contents can be validated. If not, we redirect you to inlang.com/new (in the works – maybe a bit too early to mention it in the CLI). Do you have feedback on how to make this process easier?

> The JSON schema link to be valid

Already fixed that. Valid link is: https://inlang.com/schema/project-settings – Sorry for missing that in the docs.

> The sdk-js not to be deprecated if paraglide-js is not ready yet? 

Unfortunately, the sdk-js maintainer, our colleague & friend @ivanhofer passed away 6 weeks ago. Sadly, we had no other choice than deprecating the sdk-js because of the refactor & built something new from scratch called "paraglide". One of Ivan's favorite hobbies.

> Can I use Inlang without paraglide?

Yes you can! For example with i18next. 

https://inlang.com/marketplace/plugin.inlang.i18next

But I would recommend to wait on paraglide which will be released next week because it solves near all problems other i18n libraries have. See progress & more info here in the README's https://github.com/inlang/monorepo/tree/paraglide-js/inlang/source-code/paraglide

> The docs to potentially include a Migration page

cc @samuelstroschein Will be added for sveltekit. 👍 

> And what do I do for standardLintRules?

We have decided to not go with a standard bundled package anymore but let people handle their rules individually what makes it much easier to enable / disable rules specifically. See https://github.com/inlang/monorepo/blob/main/project.inlang.json on how this works or look for Lint Rules in the Marketplace https://inlang.com/marketplace

Again, thank you for your feedback, it's really helpful! 🙏

**Comment by samuelstroschein** [comment] 2023-10-13 08:26
Hey @WarningImHack3r, 

Thank you for the elaborate issue. 

Stay on the SDK-JS for another week or so. Paraglide is nearing completion. 

- [ ] remove "manually creating a project" from the documentation as setting up a project is app specific. 
- [ ] remove "inlang project init" from CLI for a similar reason

**Comment by jannesblobel** [comment] 2023-10-13 08:40
@WarningImHack3r 
I migrated the project for you. Currently, the editor and the VS code extension work with the project.inlang.json ( see PR). But you can also wait until Paraglide is out. 
https://github.com/EmeraldHQ/Website/pull/150

**Closed** 2023-10-13 08:46 UTC
Labels: type: bug, priority: medium, scope: inlang/cli

**Comment by WarningImHack3r** [comment] 2023-10-13 10:03
Thanks for all your (quick) answers!!

> We are currently in the process of rebuilding our website and will soon offer an `inlang.com/new` where we guide you through the process of creating your inlang project. Sorry if that's not helpful for you atm, but we will have something ready in a matter of a few (2-3) weeks.

I see, my bad! Also, @samuelstroschein, I noticed your website is translated into a few languages, I can add the French translation for you if you want

> It does generate a `project.inlang.json` file for you but only if the process succeeds & the file contents can be validated. If not, we redirect you to inlang.com/new (in the works – maybe a bit too early to mention it in the CLI). Do you have feedback on how to make this process easier?

Just a line explaining that the CLI is supposed to create the file for us, that's it! But now that it's gone it's not useful anymore haha.  
However, I still don't understand why the code of the CLI was so "complicated" instead of a simple `fs.asyncWrite`; it seemed to fail in my case because of that part and not because it failed to actually generate the config. Mentioning that the problem was the writing part and not the config generation part could have been more useful, and why not printing the whole generated config in the console saying something like "Here's the new config but we failed to write it:". But once again, the command is gone so no problem anymore :D

> Already fixed that. Valid link is: [inlang.com/schema/project-settings](https://inlang.com/schema/project-settings) – Sorry for missing that in the docs.

Thanks! You can maybe add it in the [Project](https://inlang.com/documentation/project) page's JSON (not sure it's relevant), and fix the `getting started` link at the top of this very page being broken now that the getting started page is deleted. Also, I think a Getting Started page would still be relevant, even if different, in order to orient the user toward what they actually need to choose; there are a lot of concepts to understand in Inlang and it's not really obvious what you should pick when you're new to i18n or that you just want to find the right page to go to to add localization to your (SvelteKit) project.

> Unfortunately, the sdk-js maintainer, our colleague & friend @ivanhofer passed away 6 weeks ago. Sadly, we had no other choice than deprecating the sdk-js because of the refactor & built something new from scratch called "paraglide". One of Ivan's favorite hobbies.

Yes I'm aware for Ivan and that's what I mentioned in the first line of my original message, we miss it all. Can't wait for paraglide then.

> > Can I use Inlang without paraglide?
> 
> Yes you can! For example with i18next. [...] But I would recommend to wait on paraglide which will be released next week because it solves near all problems other i18n libraries have. See progress & more info here in the README's [`paraglide-js`/inlang/source-code/paraglide](https://github.com/inlang/monorepo/tree/paraglide-js/inlang/source-code/paraglide?rgh-link-date=2023-10-13T08%3A01%3A31Z)

Thanks! I'll wait, keeping my PR in draft for now (EmeraldHQ/Website#149)

> > The docs to potentially include a Migration page
> 
> cc @samuelstroschein Will be added for sveltekit. 👍

🔥

> We have decided to not go with a standard bundled package anymore but let people handle their rules individually what makes it much easier to enable / disable rules specifically. See [`main`/project.inlang.json](https://github.com/inlang/monorepo/blob/main/project.inlang.json?rgh-link-date=2023-10-13T08%3A01%3A31Z) on how this works or look for Lint Rules in the Marketplace [inlang.com/marketplace](https://inlang.com/marketplace)

I see, makes sense! I don't know if it's written anywhere in the docs, but I think it would fit perfectly into that Migration page haha

> Again, thank you for your feedback, it's really helpful! 🙏

No problem! I'm glad to help :)

**Comment by felixhaeberle** [comment] 2023-10-13 10:19
Added the `$schema` to https://inlang.com/documentation/project

**Comment by felixhaeberle** [comment] 2023-10-13 10:22
> I can add the French translation for you if you want

Yes please, I will ping you in a few days when the new website is ready! 🔥

**Comment by WarningImHack3r** [comment] 2023-10-13 10:30
> Yes please, I will ping you in a few days when the new website is ready! 🔥

So should I wait for the new website? If so, yes ping me and tell me how to localize it!

**Comment by WarningImHack3r** [comment] 2023-10-13 10:36
Thanks @samuelstroschein for that explanation video! It indeed now makes sense, I didn't know all of this code should also work for all the platforms 😅

And yeah I like that format, faster and clearer to understand (although you forgot to answer about the glob pattern support in `pathPattern` for the JSON plugin haha) :)

And as we just discussed with @felixhaeberle, I'll take a look at the French localization as soon as the new website is up, don't hesitate to ping me when it's done and where all this takes place!

**Comment by samuelstroschein** [comment] 2023-10-13 12:18
> Also, why get rid of the glob pattern support in the pathPattern of the JSON plugin? It was useful and worked well, was it a technical limitation of your new architecture?

> (although you forgot to answer about the glob pattern support in pathPattern for the JSON plugin haha) :) 

I don't recall anyone deleting the glob support on purpose. It might be a bug. cc @inlang/plugins

**Comment by WarningImHack3r** [comment] 2023-10-13 13:57
> It might be a bug. cc @inlang/plugins

@samuelstroschein wdym by this cc? I'm asking because I was using it with the plugin v3 and for the whole migration (that includes plugin v4) @jannesblobel did it individually (without globs) in EmeraldHQ/Website#150

**Comment by samuelstroschein** [comment] 2023-10-13 15:08
@WarningImHack3r tagging the plugin team to verify if this is a bug. I can confirm that this is not a bug though. You are using namespaces where we opted for explicit instead of implicit behaviour

**Comment by WarningImHack3r** [comment] 2023-10-13 15:57
Ok so globs are not supported anymore, good to know (Migration page again ;) )

**Comment by WarningImHack3r** [comment] 2023-11-07 09:32
Hi @felixhaeberle @samuelstroschein, I see inlang.com has a new look, is it ready to welcome the French translation?
What about `paraglide-js`? Is the pre-release ready to replace `sdk-js`?

**Comment by samuelstroschein** [comment] 2023-11-07 15:57
Hi @WarningImHack3r, 

As a matter of fact, yes. Inlang.com would welcome a french translation. 

> What about paraglide-js? Is the pre-release ready to replace sdk-js?

Ready but a bit of manual boilerplate needs to be written and there will be slight change today. We will announce Paraglide JS at the Svelte Summit on Nov 11. If you can wait, wait for the 11th! :)

**Comment by WarningImHack3r** [comment] 2023-11-07 16:08
Nice can't wait! How can I start translating?

**Comment by WarningImHack3r** [comment] 2023-11-07 18:34
@samuelstroschein Even after 30s I'm still in preview mode and can't add a language. Is it a bug? Do I have to fork it?

**Comment by samuelstroschein** [comment] 2023-11-07 18:43
@WarningImHack3r let me loop in @inlang/editor. @inlang/editor can you provide information on what is going on here? maybe related to #1561

**Comment by NiklasBuchfink** [comment] 2023-11-08 07:20
@WarningImHack3r This login bug will be fixed with: https://github.com/inlang/monorepo/issues/1604
A temporary fix is to delete browser cookies and try again.

The contribution flow:
1. Login with GitHub
2. Create a fork
3. Add language and translations
4. Open PR

**Comment by WarningImHack3r** [comment] 2023-11-08 07:33
> @WarningImHack3r This login bug will be fixed with: https://github.com/inlang/monorepo/issues/1604

Okay, great

> A temporary fix is to delete browser cookies and try again. Let me know if this has worked for you.

I already did clear all the website data when I tried yesterday, but no luck

> 2. Create a fork

Oh so I _have to_ fork the monorepo? Wasn't aware

**Comment by NiklasBuchfink** [comment] 2023-11-08 07:54
> Oh so I _have to_ fork the monorepo? Wasn't aware

@WarningImHack3r As you are not the owner of the repository, you should not be able to push the data directly into the repository. You can use the floating menu at the bottom to create a fork and add your changes.

![image](https://github.com/inlang/monorepo/assets/59048346/0fad6da1-efc2-488e-adcc-7d892d9e787e)

**Comment by WarningImHack3r** [comment] 2023-11-08 08:06
> @WarningImHack3r As you are not the owner of the repository, you should not be able to push the data directly into the repository.

Yeah it makes sense, but as Samuel did not mention it I thought this repo was "special" (hence the 30s wait) and that I didn't need to fork it.

Anyways, I'm gonna try again after work today :)

**Comment by NiklasBuchfink** [comment] 2023-11-08 08:19
> I thought this repo was "special" (hence the 30s wait)

Haha, I see 😄 We are working on lazy fetching of the translation files (https://github.com/inlang/monorepo/issues/1459). Until then, a repository only needs a few MBs to be "special" as we are currently cloning the entire repository.

Thank you for your patience :) ❤️
