### ISSUE TITLE
decide on `onSetLanguageTag` throwing or not approach

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1660] opened 2023-11-20 15:28 UTC
## Problem 

Paraglide's strictness for "setting" the `onSetLanguageTag` callback is causing HMR issues. 

- https://github.com/inlang/monorepo/issues/1686
- https://github.com/inlang/monorepo/discussions/1464#discussioncomment-7338784

**Comment by samuelstroschein** [comment] 2023-11-20 15:28
Not changing the behavior atm. Throwing is OK because changing to not throwing is not a breaking change. Changing the behavior from not throwing to throwing would be a breaking change however.

**Comment by samuelstroschein** [comment] 2023-11-21 22:59
Given that users run into this problem all the time, it is probably best to remove the strictness/throw. @LorisSigrist what do you think?

**Comment by LorisSigrist** [comment] 2023-11-22 09:13
Yes I agree we need to be more permissive here.
The question is how. Do we just allow many subscriptions to the language tag? 
What was the reasoning behind not doing that up until now?

**Comment by LorisSigrist** [comment] 2023-11-22 15:31
That makes sense. Should we also `console.warn` when a callback get's overridden?

**Comment by samuelstroschein** [comment] 2023-11-22 15:36
> Should we also console.warn when a callback get's overridden?

Could be super annoying in HMR. 

We can also evaluate whether the bundler plugins resolve the HMR issue and not loosen the strictness of throwing. Having an explicit throw seems better than a warning hidden in the docs or console. Except ofc if HMR sets the callback but that can be avoided with bundler adapters. 

If we expect everyone who uses bundlers to choose one of our adapters, we should be able to circumvent the issue of throws in HMR without loosening the strictness/immediate feedback "you can't set onSetLanguageTag multiple times". 

@LorisSigrist can you explore in #1669 whether you can fix the HMR issues in those adapters? If you fix it in adapters, we need tests for it ;)

**Comment by LorisSigrist** [comment] 2023-11-22 15:41
I'll see if I can make that happen!

**Comment by LorisSigrist** [comment] 2023-11-24 07:45
@samuelstroschein 
We need to re-discuss this. 

I have been able to reproduce the HMR issues thanks to @KraXen72. They only happen if the callback isn't inlined. 
In order for HMR to work, it needs to be able to reassign the callback. We can't make this work in the adapters like we thought. 

I'll reopen #1699

**Comment by samuelstroschein** [comment] 2023-11-24 14:34
@LorisSigrist that's what I thought. Okay, reassigning it is. I hope that we don't trigger regression bugs/unexpected behavior.

**Closed** 2023-11-24 14:39 UTC
Labels: scope: inlang/paraglide-js
