### ISSUE TITLE
[bug] web editor: a translation key losing focus while editing and no keys present automaticlly deletes it

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1704] opened 2023-11-22 16:55 UTC
### Problem

when i'm moving around some values in the web editor, i cannot leave a key empty, otherwise it will get deteled
there is no option to undo the key auto-deletion

i suggest the following: 
- explicit key delete button instead of auto-deleting an empty key
- undo history

### Expected behavior

key would only get deleted if i hit enter and it's empty

### Reproduction

go to web editor
remove the source value of a key in the intention to paste it somewhere else/do something with it
click off
key dissapears

### Other information

vivaldi latest stable
windows 10

**Comment by NiklasBuchfink** [comment] 2023-11-23 15:02
@KraXen72 It doesn't get deleted within the editor; it gets sorted to the end of the list. I will check why this is the case 👍 

I chose to delete the key instead of leaving the key with an empty value. This always happens when you leave an empty field and it is empty. It's easier to handle fallbacks for this case in the code.

I agree, that the sorting is unexpected. Until the problem is fixed, copying and pasting instead of cutting and pasting worked for me.

**Comment by NiklasBuchfink** [comment] 2023-11-29 17:15
@KraXen72 This is fixed now with #1769 ✅

What went wrong: We implemented a watcher that sets the messages multiple times after each update. As we always display the messages according to the structure in the reference language file, this message no longer exists in the file and has been sorted to the end of the list.

Now we only do it once (as before) and the sorting remains the same.

**Closed by NiklasBuchfink** 2023-11-29 17:15 UTC
Labels: type: bug, scope: inlang/fink-editor

**Comment by KraXen72** [comment] 2023-11-29 17:18
pog

**Comment by KraXen72** [comment] 2023-11-29 17:21
can i just say a massive thank you to the entire inlang team? 
it's been a long time since i worked with an open-source library whose devs were so helpful, nice and responsive as you guys. i truly believe you are building something great <33
