### ISSUE TITLE
inlang machine translate naively translates everything and thereby overwrites existing translations

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1482] opened 2023-10-17 18:08 UTC
## Problem 

`inlang machine translate` naively translates everything and thereby overwrites existing translations: 

- long command execution because everything, regardless of existing translations, is translated
- absolutely not production ready to the point that user write workaround scripts see https://github.com/osmosis-labs/osmosis-frontend/blob/stage/fix-machine-translate.js

## Proposal

```ts
test("it should not overwrite existing translations", async () => {})
```

**Comment by felixhaeberle** [comment] 2023-10-17 21:57
@samuelstroschein Actually I have never seen this before but it seems to have occurred in osmosis repository twice — but couldn't reproduce it twice. 

We probably should not only skip on already translated values (except empty string), but another optimization could be to not update the message if it's equal in

https://github.com/inlang/monorepo/blob/ff2429c62ca5c4aa9443f18ca66f63249668784f/inlang/source-code/cli/src/commands/machine/translate.ts#L88

Therefore, all apps would benefit from it and we can guarantee existing data, if equal, does not get overwritten / does not cause a file write.

**Comment by felixhaeberle** [comment] 2023-10-31 11:32
I'll look into it.

**Comment by felixhaeberle** [comment] 2023-10-31 15:21
closing because can't reproduce. please reopen if this occurs again.

**Closed by felixhaeberle** 2023-10-31 15:21 UTC
Labels: type: improvement, effort: low, scope: inlang/cli
