### ISSUE TITLE
[bug] IDE Extension spams Telemetry 

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1670] opened 2023-11-21 12:15 UTC
### Problem

IDE Extension spams Telemetry.

<img width="1152" alt="Screenshot 2023-11-21 at 13 11 57" src="https://github.com/inlang/monorepo/assets/43482866/28069e18-c4f1-4563-b2d2-8007d13a3e0c">

Presumably we have one of those infinite retry-bugs triggering an event each time

### Expected behavior

Get one Event for Project Loaded

### Reproduction

No Idea

@inlang/ide-extension

**Comment by felixhaeberle** [comment] 2023-11-21 16:01
duplicate of https://github.com/inlang/internal/issues/174

**Closed by felixhaeberle** 2023-11-21 16:01 UTC
Labels: type: bug
